# Generated by Django 5.0 on 2023-12-15 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField(auto_now_add=True)),
                ('street', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{2}-{0,1}[0-9]{3}$')])),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{3}-{0,1}[0-9]{3}-{0,1}[0-9]{3}$')])),
                ('status', models.CharField(choices=[('HI', 'Hired'), ('HO', 'Holidays'), ('FI', 'Fired')], max_length=2)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('pk', 'first_name', 'last_name', 'created'),
            },
        ),
    ]
