# Generated by Django 5.0 on 2023-12-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('pk', 'firstName', 'lastName', 'created')},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='birth_date',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='postal_code',
            new_name='postalCode',
        ),
    ]
