# Generated by Django 5.0 on 2024-05-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transactions_name_alter_transactions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
